### ISSUE TITLE
Change `User.has_one :investor`?

### ISSUE THREAD

**Issue by jreut** [Thrillberg/imperial-old#122]
I would bet we never refer to the `User.has_one :investor, through: :games` association. What would we mean when we say `User#investor`? Indeed, a user _has many_ investors. The association doesn't even need to be `through: :games`. This `has_many` association is just the inverse of `Investor.belongs_to :user`.

```ruby
class User < ApplicationRecord
  has_many :investors
end
```

We have a method, [`User#convert_to_investor(game)`](https://github.com/Thrillberg/imperial/blob/423103cda11017c8dcae71f63bfc3ce83ab86444/app/models/user.rb#L14-L16). It might be possible to use this new association in that method:.
```ruby
class User < ApplicationRecord
  has_many :investors

  def convert_to_investor(game)
    create_investor(game: game)
  end
end
```

Indeed, we could then forego the indirection and replace occurrences of

```ruby
user.convert_to_investor(game)
```

to become

```ruby
user.create_investor(game: game)
```

and delete `#convert_to_investor`. We would need to set a default for for `has_investor_card`, but that's not so hard to add a [default value to this column](https://github.com/Thrillberg/imperial/blob/423103cda11017c8dcae71f63bfc3ce83ab86444/db/schema.rb#L84) (actually, I think it might already implicitly default to `false`).

What do you think? Even if we don't delete `#convert_to_investor`, I think there's still a little win in using associations to construct new records instead of using `Investor.create` itself.

---

P.S. I'm not actually sure you'd get a `create_<association>` method on `User`, but 🤷‍♂️ I know not how Rails works.

**Comment by Thrillberg** [comment]
Good find! Addressed in https://github.com/Thrillberg/imperial/pull/126/commits/1e7cb089e010181332fb17d023f7ab0ab959c2bd
